apiVersion: v1
kind: Namespace
metadata:
  name: example-basicoperator
---
apiVersion: basic-operator.example.io/v1alpha1
kind: HelloWorld
metadata:
  name: example
  namespace: example-basicoperator
spec:
  kuardLabel: blue
  createLoadBalancer: true
  nodeSelector:
    kubernetes.io/os: linux
